; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:hx3_esp32]
framework = arduino
platform = espressif32
board = dfrobot_firebeetle2_esp32e
board_build.filesystem = littlefs
monitor_speed = 115200
upload_protocol = esptool
upload_speed = 921600
upload_port = COM12
monitor_filters = esp32_exception_decoder

lib_deps =
  Arduino
  littlefs
  https://github.com/bblanchon/ArduinoJson/archive/v5.13.5.zip
  https://github.com/ESP32Async/ESPAsyncWebServer.git
  https://github.com/ESP32Async/AsyncTCP.git
  https://github.com/arduino/arduino-esp32/archive/refs/heads/master.zip
  

build_flags =
	-D SUPPORT_TRANSACTIONS
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
  

[env:hx3_esp32_ideaspark]
framework = arduino
platform = espressif32
board = dfrobot_firebeetle2_esp32e
board_build.filesystem = littlefs
monitor_speed = 115200
upload_protocol = esptool
upload_speed = 921600
upload_port = COM13
monitor_filters = esp32_exception_decoder

lib_deps =
  Arduino
  littlefs
  https://github.com/bblanchon/ArduinoJson/archive/v5.13.5.zip
  https://github.com/ESP32Async/ESPAsyncWebServer.git
  https://github.com/ESP32Async/AsyncTCP.git
  https://github.com/arduino/arduino-esp32/archive/refs/heads/master.zip
  https://github.com/ayushsharma82/ElegantOTA/archive/refs/heads/master.zip
 	https://github.com/Bodmer/TFT_eSPI/archive/refs/heads/master.zip
 
build_flags =
	-D SUPPORT_TRANSACTIONS
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
  -D PANEL_ESP
  -D USER_SETUP_LOADED=1
	-D ST7789_DRIVER
	-D TFT_CS=15
	-D TFT_DC=2
	-D TFT_RST=4
	-D TFT_MOSI=23
	-D TFT_MISO=-1
	-D TFT_SCLK=18
  -D TFT_BL=32
  -D TOUCH_CS=-1
  -D TFT_WIDTH=170
  -D TFT_HEIGHT=320
  -D LOAD_FF
	-D LOAD_GLCD
	-D LOAD_FONT2
	-D LOAD_FONT4
  -D LOAD_FONT7
	-D LOAD_GFXFF
	-D SPI_FREQUENCY=50000000
	-D SPI_READ_FREQUENCY=16000000

[env:hx3_esp32_nv3007]
framework = arduino
platform = espressif32
board = dfrobot_firebeetle2_esp32e
board_build.filesystem = littlefs
monitor_speed = 115200
upload_protocol = esptool
upload_speed = 921600
upload_port = COM13
monitor_filters = esp32_exception_decoder

lib_deps =
  Arduino
  littlefs
  https://github.com/bblanchon/ArduinoJson/archive/v5.13.5.zip
  https://github.com/ESP32Async/ESPAsyncWebServer.git
  https://github.com/ESP32Async/AsyncTCP.git
  https://github.com/arduino/arduino-esp32/archive/refs/heads/master.zip
  https://github.com/ayushsharma82/ElegantOTA/archive/refs/heads/master.zip
 	https://github.com/Bodmer/TFT_eSPI/archive/refs/heads/master.zip
 
build_flags =
	-D SUPPORT_TRANSACTIONS
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
  -D PANEL_ESP
  -D USER_SETUP_LOADED=1
	-D NV3007_DRIVER
  -D TFT_WIDTH=142
  -D TFT_HEIGHT=428
	-D TFT_CS=15
	-D TFT_DC=2
	-D TFT_RST=4
	-D TFT_MOSI=23
	-D TFT_MISO=-1
	-D TFT_SCLK=18
  -D TFT_BL=32
  -D TOUCH_CS=-1
  -D LOAD_FF
	-D LOAD_GLCD
	-D LOAD_FONT2
	-D LOAD_FONT4
  -D LOAD_FONT7
	-D LOAD_GFXFF
	-D SPI_FREQUENCY=20000000
	-D SPI_READ_FREQUENCY=16000000